routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\PhotoController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Route::resource('/blogs', BlogController::class,
['parameters' => ['blogs' => 'blog_id',]]);

Route::post('/uploadImage', [PhotoController::class,'uploadImage']);

app/Models/Blog.php
<?php

namespace App\Models;

use App\Trait\ModelTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Blog extends Model
{
    use HasFactory, SoftDeletes, ModelTrait;

    protected $table = 'blogs';

    protected $fillable = ['name', 'description', 'img_caver', 'user_id'];

    protected $hidden = ['updated_at', 'deleted_at'];

    protected $dates = [];

    protected $casts = [];

    public function parageaph()
    {
        return $this->hasMany(Paragraph::class);
    }

    public function tags()
    {
        return $this->hasManyThrough(
            Tag::class,
            BlogTag::class,
            'blog_id',
            'id',
            'id',
            'tag_id'
        );
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function userBlog($userId)
    {
        return $this->where('user_id', $userId)->get();
    }

    public function show($blogId)
    {
        return $this->where('id', $blogId)->with('parageaph.photo','tags')->first();
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DestroyRequest;
use App\Http\Requests\ShowRequest;
use App\Http\Requests\StoreRequest;
use App\Http\Requests\UpdateRequest;
use App\Models\Blog;
use App\Models\BlogTag;
use App\Models\Paragraph;
use App\Models\Photo;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BlogController extends Controller
{

    private $blog, $paragraph, $pohto;

    public function __construct(Blog $blog, Paragraph $paragraph, Photo $pohto)
    {
        $this->blog = $blog;
        $this->paragraph = $paragraph;
        $this->pohto = $pohto;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $blogs = $this->blog->all();
        return view('blogs.index', compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags=(new Tag())->all();
        return view('blogs.create',compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $blogData = $request->only('name', 'description', 'img_caver');
        $blogCreated = $this->blog->createData($blogData);
        //paragraphs
        $paragraphs = $request->get('paragraphs');
        $this->blogDetail($blogCreated->id, $paragraphs);
        //tag
        if($request->filled('tag_ids')){
            $tagIds=$request->get('tag_ids');
            $this->tags($blogCreated->id,$tagIds);
        }

        return response()->json('created successfully', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(ShowRequest $request)
    {
        $id = $request->validated();
        $blog = $this->blog->show($id['blog_id']);
        return view('blogs.show', compact('blog'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(ShowRequest $request)
    {
        $tags=(new Tag())->all();
        $id = $request->validated();
        $blog = $this->blog->show($id['blog_id']);
        return view('blogs.edit', compact('blog','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request)
    {
        $data = $request->validated();
        $blogId = $data['blog_id'];
        unset($data['blog_id']);
        $blogData = $request->only('name', 'description', 'img_caver');
        $blogCreated = $this->blog->updateData(['id'=>$blogId],$blogData,);

        $paragraphs = $request->get('paragraphs');
        $this->blogDetail($blogId, $paragraphs, true);
        //tag
        if($request->filled('tag_id'))
            $this->tags($blogCreated->id,$request->get('tag_id'),true);

        return response()->json('updated successfully', 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(DestroyRequest $request)
    {
        $id = $request->validated();
        $this->deleteDetail($id['blog_id']);
        $this->blog->deleteData(['id'=>$id['blog_id']]);
        return redirect()->route('blogs.index')
            ->with('success', 'Blog deleted successfully');
    }

    public function blogDetail($blogId, $paragraphs, $isUpdate = false)
    {
        if ($isUpdate) $this->deleteDetail($blogId);

        foreach ($paragraphs as $paragraph) {
            $paragraphData['text'] = $paragraph['text'];
            $paragraphData['blog_id'] = $blogId;
            $paragraphCrrated = $this->paragraph->createData($paragraphData);
            if (!blank($paragraph['img_urls'])) {
                $photoData = [];
                foreach ($paragraph['img_urls'] as $imgUrl) {
                    if (!blank($imgUrl)){
                        $temp['img_url'] = $imgUrl;
                        $temp['paragraph_id'] = $paragraphCrrated->id;
                        $temp['created_at'] = Carbon::now();
                        $temp['updated_at'] = Carbon::now();
                        array_push($photoData, $temp);
                    }
                }
                $this->pohto->insertData($photoData);
            }
        }
        return true;
    }

    public function deleteDetail($blogId)
    {
        $paragraphs = $this->paragraph->getData(['blog_id' => $blogId]);
        if(!blank($paragraphs)){
            $paragraphIds = $paragraphs->pluck('id')->toArray();
            $find= $this->pohto->getData($paragraphIds);
            if(!blank($find))
                $this->pohto->deleteData( $paragraphIds);
            $this->paragraph->deleteData(['blog_id' => $blogId]);
        }
        return true;
    }

    public function tags($blogId, $tagsIds, $isUpdate=false)
    {
        if($isUpdate) (new BlogTag())->deleteData($tagsIds);

        $blogTagData=[];
        foreach($tagsIds as $id){
            $temp['blog_id']=$blogId;
            $temp['tag_id']=$id;
            $temp['created_at']=Carbon::now();
            $temp['updated_at']=Carbon::now();
            array_push($blogTagData,$temp);
        }
        (new BlogTag())->insertData($blogTagData);
        return true;
    }
}

resources/views/blogs/create.blade.php
@extends('blogs.layout')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Blog</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Warning!</strong> Please check your input code<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>name:</strong>
                <input required type="text" name="name" id="name" class="form-control" placeholder="name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>tags:</strong>
                <input type="text" class="form-control" id="tags_name" readonly>
                <input type="text" hidden id="tag_ids">
                <select name="tags" class="form-control" id="tags">
                    <option value=""></option>
                    @foreach ($tags as $tag)
                        <option value="{{$tag->id}}">{{$tag->tag}}</option>
                    @endforeach
                  </select>
            </div>
            <div class="form-group">
                <strong>Description:</strong>
                <textarea required class="form-control" id="description" style="height:50px" name="description" placeholder="Description"></textarea>
                <strong>Add caver photo:</strong>
                <input required id="img_caver"  type="file" name="img_caver" class="btn btn-primary" value="Add caver photo">
                <input type="text" hidden id="url_img_caver">
                <div id="paragraphs">
                    <div class="paragraphLength" ><br>
                        <strong>paragraph:</strong>
                        <textarea  required class="form-control text" style="height:100px" name="text" placeholder="paragraph" ></textarea>
                        <input multiple required id="img_url"  type="file" name="img_url" class="btn btn-primary" value="Add photo">
                        <input type="text" hidden class="urls">
                    </div>
                </div>
                <input type="button" class="btn btn-success" onclick="addparagraph()" value="Add paragraph">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-right">
                <button onclick="submit()" type="submit" class="btn btn-primary">Submit</button>
                <meta name="csrf-token" content="{{ csrf_token() }}">

        </div>
    </div>

<script>
    var tag_ids = new Array();
    $(document).on('change','#tags',(e)=>{
        var tag=document.getElementById('tags').value;
        var tag_select=$( "#tags option:selected" ).text();
        var tags_name=document.getElementById('tags_name').value;
        if(tag != ''){
            $('#tags_name').val(tag_select+' '+tags_name);
            tag_ids.push(tag);
        }
    });

    $(document).on('change','#img_caver',(e)=>{
        var img=e.target.files[0];
        var files = new FormData();
        files.append('imgs[]',img);
        $.ajax({
            url:'/uploadImage',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:"post",
            dataType :"json",
            data: files,
            contentType: false,
            processData: false,
        }).done((url)=>{
            console.log(url);
            $('#url_img_caver').val(url);
        })
    });

    $(document).on('change','#img_url',(e)=>{
        var imgs=e.target.files;
        console.log(imgs[0]);
        var files = new FormData();
        for (var x = 0; x < imgs.length ; x++) {
            files.append("imgs[]", imgs[x]);
        }
        $.ajax({
            url:'/uploadImage',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:"post",
            data: files,
            processData: false,
            contentType: false,
        }).done((url)=>{
            console.log(url);
            var row = $(e.target);
            row.closest('.paragraphLength').find('.urls').val(url);
        });
    });

    function addparagraph() {
        $('#paragraphs').append(`
            <div class="paragraphLength" >
            <strong>paragraph:</strong>
            <textarea required class="form-control text" style="height:100px" name="text" placeholder="paragraph" ></textarea>
            <input multiple required  id="img_url"  type="file" name="img_url" class="btn btn-primary" value="Add photo">
            <input type="text" hidden class="urls">
            </div>
        `)
    }

    function  submit(){
        var blog = new Array();
        blog['name']=document.getElementById('name').value;
        blog['description']=document.getElementById('description').value;
        blog['img_caver']=document.getElementById('url_img_caver').value;
        var paragraph=[]
        var urls = document.getElementsByClassName('urls');
        var texts = document.getElementsByClassName('text');
        for (let index = 0; index < urls.length; index++) {
            const element = urls[index];
            const pp = texts[index];
            paragraph.push({
                text:pp.value,
                img_urls:element.value.split(','),
            });
        }
        blog['paragraph'] =paragraph;
        $.ajax({
        url:'/blogs',
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        method:"post",
        dataType :"json",
        data:{
            name:blog['name'],
            tag_ids:tag_ids,
            description:blog['description'],
            img_caver:blog['img_caver'],
            paragraphs:blog['paragraph']
        },
        }).done((url)=>{
            window.location.href = "/blogs";
        });
    }
</script>
@endsection

resources/views/blogs/edit.blade.php
@extends('blogs.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Blog</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Warning!</strong> Please check input field code<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>name:</strong>
                    <input type="text" name="name" id="name" value="{{ $blog->name }}" class="form-control" placeholder="name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>tags:</strong>
                    <input type="button"  id="clear_tags" value="clear" onclick="clear_tag()">
                    <input type="text" class="form-control" id="tags_name" readonly>
                    <input hidden type="text" id="blog_tag" value={{$blog->tags}} readonly>
                    <select name="tags" class="form-control" id="tags">
                        <option value=""></option>
                        @foreach ($tags as $tag)
                            <option value="{{$tag->id}}">{{$tag->tag}}</option>
                        @endforeach
                      </select>
                </div>
                <div class="form-group">
                    <strong>Description:</strong><strong>Add caver photo:</strong>
                    <textarea class="form-control" style="height:50px" name="description" id="description" placeholder="Description">{{ $blog->description }}</textarea>
                    <input required id="img_caver"  type="file" name="img_caver" class="btn btn-primary" value="Add caver photo">
                    <input type="text" hidden id="url_img_caver" value="{{ $blog->img_caver }}">you have caver photo need to change it <br>
                    <div id="paragraphs">
                        <div class="paragraphLength" >
                            @php($urls='')
                            @foreach ($blog->parageaph as $item )
                                <strong>paragraph:</strong>
                                <textarea class="form-control text" style="height:100px" name="text" placeholder="paragraph" >{{ $item->text }}</textarea>
                                <input multiple  id="img_url"  type="file" name="img_url" class="btn btn-primary" value="Add photo">
                                @if (!blank($item->photo))
                                    @foreach ($item->photo as $imgs )
                                    @php($urls .=$imgs->img_url . ',')
                                    @endforeach
                                @endif
                                <input type="text" hidden class="urls" value="{{$urls}}">
                                you have {{count($item->photo)}} photo do you need to change<br>
                                @php($urls='')
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-right">
                <button onclick="submit()" type="submit" class="btn btn-primary">Edit</button>
                <meta name="csrf-token" content="{{ csrf_token() }}">
            </div>
        </div>

<script>

var tag_ids = new Array();

$( document ).ready(function() {
    var tags = {!! json_encode($blog->tags) !!}
    for (let i = 0; i < tags.length ; i++) {
        var tags_name=document.getElementById('tags_name').value;
        $('#tags_name').val(tags_name +' '+ tags[i]['tag']);
        tag_ids.push(tags[i]['id']);
    }
});

function clear_tag(){
    $('#tags_name').val('');
    tag_ids=[];
}

    $(document).on('change','#tags',(e)=>{
        var tag=document.getElementById('tags').value;
        var tag_select=$( "#tags option:selected" ).text();
        var tags_name=document.getElementById('tags_name').value;
        if(tag != ''){
            $('#tags_name').val(tag_select+' '+tags_name);
            tag_ids.push(tag);
        }
    });

$(document).on('change','#img_caver',(e)=>{
        var img=e.target.files[0];
        var files = new FormData();
        files.append('imgs[]',img);
        $.ajax({
            url:'/uploadImage',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:"post",
            dataType :"json",
            data: files,
            contentType: false,
            processData: false,
        }).done((url)=>{
            console.log(url);
            $('#url_img_caver').val(url);
        })
    });

    $(document).on('change','#img_url',(e)=>{
        var imgs=e.target.files;
        console.log(imgs[0]);
        var files = new FormData();
        for (var x = 0; x < imgs.length ; x++) {
            files.append("imgs[]", imgs[x]);
        }
        $.ajax({
            url:'/uploadImage',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:"post",
            data: files,
            processData: false,
            contentType: false,
        }).done((url)=>{
            console.log(url);
            var row = $(e.target);
            row.closest('.paragraphLength').find('.urls').val(url);
        });
    });

    function  submit(){
        var name=document.getElementById('name').value;
        var description=document.getElementById('description').value;
        var img_caver=document.getElementById('url_img_caver').value;
        var paragraph=[];
        var urls = document.getElementsByClassName('urls');

        var texts = document.getElementsByClassName('text');
        for (let index = 0; index < urls.length; index++) {
            const element = urls[index];
            const pp = texts[index];
            paragraph.push({
                text:pp.value,
                img_urls:element.value.split(','),
            });
        }
        console.log(paragraph);
        $.ajax({
        url:'/blogs/{{$blog->id}}',
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        },
        dataType :"json",
        method:"put",
        data:{
            name:name,
            description:description,
            img_caver:img_caver,
            paragraphs:paragraph
        },
        }).done((url)=>{
            window.location.href = "/blogs";
        });
    }
</script>
@endsection

resources/views/blogs/index.blade.php
@extends('blogs.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Check all Blogs</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('blogs.create') }}"> Create new blogs</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Title</th>
            <th>Description</th>
            <th width="250px">Action</th>
        </tr>
        @foreach ($blogs as $blog)
        <tr>
            <td>{{ $blog->id }}</td>
            <td>{{ $blog->name }}</td>
            <td>{{ $blog->description }}</td>
            <td>
                <form action="{{ route('blogs.destroy',$blog->id) }}" method="POST">

                    <a class="btn btn-info" href="{{ route('blogs.show',$blog->id) }}">Show</a>

                    <a class="btn btn-primary" href="{{ route('blogs.edit',$blog->id) }}">Edit</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
@endsection

resources/views/blogs/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Main layout page </title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src = "https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<style>

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 12px 16px;
  z-index: 1;
}
    img {
      display: block;
      margin-left: auto;
      margin-right: auto;
    }
</style>
</head>
<body>
<div class="jumbotron text-center">
  <h1> Toughts </h1>
  <p>By: Ahmad Helali</p>
</div>

<div class="container">
    @yield('content')
</div>
<div class="jumbotron text-center" style="margin-bottom:0">
  <p>Footer</p>
</div>
</body>
</html>

resources/views/blogs/show.blade.php
@extends('blogs.layout')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
            </div>
        </div>
    </div>
<br>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <h5><strong>tags:</strong>
                @if(!blank($blog->tags))
                    @foreach ($blog->tags as $tag)
                        {{$tag->tag}}
                    @endforeach
                @endif
            </h5>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <h1><strong>Name:</strong>
                {{ $blog->name }}</h1>
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Description:</strong>
                {{ $blog->description }}
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <img height="300" width="600" src={{ $blog->img_caver }}>
            </div>
        </div>

        @foreach ($blog->parageaph as $item )
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    {{ $item->text }}
                </div>
            </div>
            @foreach ($item->photo as $img)
                @if ($img!=[])
                    <div class="col-xs-6 col-sm-6 col-md-6">
                        <div class="form-group">
                            <img src={{ $img->img_url }}>
                        </div>
                    </div>
                @endif
            @endforeach
        @endforeach
    </div>
@endsection